image: node:18

definitions:
  caches:
    yarn: $HOME/.cache/yarn
  services:
    docker:
      memory: 2048


pipelines:
  branches:
    development:
      - step:
          name: Install dependencies
          caches:
            - yarn
            - node
          script:
            - yarn install --frozen-lockfile
          artifacts:
            - node_modules/**
            - .next/**

      - step:
          name: Lint
          script:
            - yarn lint
          artifacts:
            - .eslintcache

      - step:
          name: Type check
          script:
            - yarn tsc --noEmit

      - step:
          name: Build
          script:
            - yarn build
          artifacts:
            - .next/**

      - step:
          name: Test
          script:
            - yarn test || echo "No tests found, skipping tests"

      - step:
          name: Build and push Docker image
          services:
            - docker
          script:
            - export IMAGE_NAME=$DOCKER_REGISTRY/nextjs-app
            - export IMAGE_TAG=dev-$BITBUCKET_COMMIT
            - echo "Building Docker image ${IMAGE_NAME}:${IMAGE_TAG}"
            - docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:development .
            - echo "Logging in to Docker registry"
            - echo $DOCKER_PASSWORD | docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME --password-stdin
            - echo "Pushing Docker image"
            - docker push $IMAGE_NAME:$IMAGE_TAG
            - image-details.txt

      - step:
          name: Summary
          script:
            - echo "Pipeline completed successfully!"
